# Generated by Django 4.1.7 on 2023-02-25 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_api", "0001_initial"),
        ("user_api", "0001_initial"),
        ("account_api", "0001_initial"),
        ("bank_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=99)),
                ("transaction_status", models.CharField(max_length=20)),
                ("transaction_type", models.CharField(max_length=20)),
                ("transaction_with", models.CharField(max_length=50)),
                ("purpose", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "accountid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_api.account",
                    ),
                ),
                (
                    "bankid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank_api.bank"
                    ),
                ),
                (
                    "compid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_api.company",
                    ),
                ),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_api.user"
                    ),
                ),
            ],
        ),
    ]
