# Generated by Django 4.1.7 on 2023-02-25 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="accountid",
            new_name="account_id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="bankid",
            new_name="bank_id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="companyid",
            new_name="company_id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transactionid",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transactionstatus",
            new_name="transaction_status",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transactiontype",
            new_name="transaction_type",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="transactionwith",
            new_name="transaction_with",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="userid",
            new_name="user_id",
        ),
    ]
