# Generated by Django 4.1.7 on 2023-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_api", "0004_rename_account_transaction_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_status",
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(max_length=99),
        ),
    ]
