# Generated by Django 4.1.7 on 2023-02-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_api", "0005_alter_transaction_transaction_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="account_id",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account_number",
            field=models.CharField(default=None, max_length=99, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_with",
            field=models.CharField(max_length=99),
        ),
    ]
