# Generated by Django 4.1.7 on 2023-02-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction_api", "0006_remove_transaction_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account_number",
            field=models.CharField(max_length=99),
        ),
    ]
