# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_api", "0001_initial"),
        ("bank_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("accountid", models.AutoField(primary_key=True, serialize=False)),
                ("accountnumber", models.CharField(max_length=20, unique=True)),
                ("accountname", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                ("branchcode", models.CharField(max_length=30)),
                ("purpose", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, max_digits=99),
                ),
                ("creditlimit", models.DecimalField(decimal_places=2, max_digits=99)),
                (
                    "bankid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank_api.bank"
                    ),
                ),
                (
                    "companyid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_api.company",
                    ),
                ),
            ],
        ),
    ]
