# Generated by Django 4.1.7 on 2023-02-25 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_api", "0001_initial"),
        ("bank_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("accountnum", models.CharField(max_length=20, unique=True)),
                ("accountname", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                ("branchcode", models.CharField(max_length=30)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("purpose", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "accountbalance",
                    models.DecimalField(decimal_places=2, max_digits=99),
                ),
                ("creditlimit", models.DecimalField(decimal_places=2, max_digits=99)),
                (
                    "bankid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank_api.bank"
                    ),
                ),
                (
                    "compid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_api.company",
                    ),
                ),
            ],
        ),
    ]
