# Generated by Django 4.1.7 on 2023-02-25 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_api", "0002_rename_accountid_account_account_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="bank_id",
            new_name="bank",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="company_id",
            new_name="company",
        ),
    ]
