# Generated by Django 4.1.7 on 2023-02-25 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="bankid",
            new_name="bank_id",
        ),
        migrations.RenameField(
            model_name="bank",
            old_name="bankname",
            new_name="bank_name",
        ),
    ]
