# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("companyid", models.AutoField(primary_key=True, serialize=False)),
                ("companyname", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("pan", models.CharField(max_length=10, unique=True)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
