# Generated by Django 4.1.7 on 2023-02-25 07:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("accountnum", models.CharField(max_length=20, unique=True)),
                ("accountname", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                ("branchcode", models.CharField(max_length=30)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("purpose", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "accountbalance",
                    models.DecimalField(decimal_places=2, max_digits=99),
                ),
                ("creditlimit", models.DecimalField(decimal_places=2, max_digits=99)),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "bankid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bankname", models.CharField(max_length=500)),
                ("hqlocation", models.CharField(blank=True, max_length=500, null=True)),
                ("hqpincode", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "compid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("compname", models.CharField(max_length=200)),
                ("hqlocation", models.CharField(blank=True, max_length=500, null=True)),
                ("pan", models.CharField(max_length=10, unique=True)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("hqpincode", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                ("organisation", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "aadhar",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "pan",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "compid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dashb.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("transaction_status", models.CharField(max_length=20)),
                ("transaction_type", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=99)),
                ("purpose", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField()),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fromaccount",
                        to="dashb.account",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toaccount",
                        to="dashb.account",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="bankid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashb.bank"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="compid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashb.company"
            ),
        ),
    ]
