# Generated by Django 4.1.7 on 2023-02-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("transactionid", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=20)),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "aadhar",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                (
                    "pan",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "companyid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company_api.company",
                    ),
                ),
            ],
        ),
    ]
