# Generated by Django 4.1.7 on 2023-02-25 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="companyid",
            new_name="company_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="transactionid",
            new_name="transaction_id",
        ),
    ]
