# Generated by Django 4.1.7 on 2023-02-25 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0002_rename_companyid_user_company_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="transaction_id",
            new_name="user_id",
        ),
    ]
