# Generated by Django 4.1.7 on 2023-02-25 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0003_rename_transaction_id_user_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company_id",
            new_name="company",
        ),
    ]
