# Generated by Django 4.1.7 on 2023-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0005_rename_company_user_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="aadhar",
            field=models.CharField(blank=True, max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="pan",
            field=models.CharField(blank=True, max_length=99, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=99),
        ),
    ]
